module

public import FluidSingularSets.Geometry
public import FluidSingularSets.Gauge
public import FluidSingularSets.BoxDimension
public import FluidSingularSets.BoxFromCharge
public import FluidSingularSets.Packing
public import FluidSingularSets.PersistentActivity
public import FluidSingularSets.WeightedActivity
public import FluidSingularSets.MovingScale
public import FluidSingularSets.TraceLayerCake
public import FluidSingularSets.IteratedGauge
public import FluidSingularSets.IteratedLogSeries
public import FluidSingularSets.IteratedActivity
public import FluidSingularSets.RegularSet
public import FluidSingularSets.CKNBridge
public import FluidSingularSets.CKNBaseline
public import FluidSingularSets.ActivityTrace
public import FluidSingularSets.CarlesonEmbedding
public import FluidSingularSets.MassRatioStopping
public import FluidSingularSets.CountableCarleson
public import FluidSingularSets.MixedGradient
public import FluidSingularSets.CriticalSobolev
public import FluidSingularSets.RegularityBridge
public import FluidSingularSets.ParabolicDyadic
public import FluidSingularSets.FrostmanCarleson
public import FluidSingularSets.AdjacentIntervals
public import FluidSingularSets.IteratedScaling
public import FluidSingularSets.LogProductComparison
public import FluidSingularSets.LogGaugeRegularity
public import FluidSingularSets.MassRatioTrace
public import FluidSingularSets.IntegratedCarleson
public import FluidSingularSets.ShiftedParabolicDyadic
public import FluidSingularSets.CriticalPoincare
public import FluidSingularSets.ScaleRegularity
public import FluidSingularSets.GaugeFrostman
public import FluidSingularSets.ShiftedCarleson
public import FluidSingularSets.RealCharge
public import FluidSingularSets.CompactLocalization
public import FluidSingularSets.TraceCost
public import FluidSingularSets.ParabolicRefinement
public import FluidSingularSets.GaugeFrostmanLimit
public import FluidSingularSets.GaugeTransport
public import FluidSingularSets.MixedPressure
public import FluidSingularSets.ActivityMeasurability
public import FluidSingularSets.ParabolicFrostmanGeometry
public import FluidSingularSets.GaugeFrostmanApproximations
public import FluidSingularSets.GaugeFrostmanConstruction
public import FluidSingularSets.SpatialTraceCoefficients
public import FluidSingularSets.ShiftedSpatialRepresentation
public import FluidSingularSets.MixedVelocityDecay

/-! # Singular-set refinements for suitable weak Navier–Stokes solutions

This root exports the completed supporting development. The three target declarations for the
two requested results are in `Challenge.lean`. Main proof completion is tracked separately in
`Solution.lean`.
-/
