module

public import FluidSingularSets.Geometry
public import FluidSingularSets.Gauge
public import FluidSingularSets.BoxDimension
public import FluidSingularSets.BoxFromCharge
public import FluidSingularSets.Packing
public import FluidSingularSets.PersistentActivity
public import FluidSingularSets.WeightedActivity
public import FluidSingularSets.MovingScale
public import FluidSingularSets.TraceLayerCake
public import FluidSingularSets.IteratedGauge
public import FluidSingularSets.IteratedLogSeries
public import FluidSingularSets.IteratedActivity
public import FluidSingularSets.RegularSet
public import FluidSingularSets.CKNBridge
public import FluidSingularSets.CKNBaseline
public import FluidSingularSets.ActivityTrace
public import FluidSingularSets.CarlesonEmbedding
public import FluidSingularSets.MassRatioStopping
public import FluidSingularSets.CountableCarleson
public import FluidSingularSets.MixedGradient
public import FluidSingularSets.CriticalSobolev
public import FluidSingularSets.RegularityBridge
public import FluidSingularSets.ParabolicDyadic
public import FluidSingularSets.FrostmanCarleson
public import FluidSingularSets.AdjacentIntervals
public import FluidSingularSets.IteratedScaling
public import FluidSingularSets.LogProductComparison
public import FluidSingularSets.LogGaugeRegularity
public import FluidSingularSets.MassRatioTrace
public import FluidSingularSets.IntegratedCarleson
public import FluidSingularSets.ShiftedParabolicDyadic
public import FluidSingularSets.CriticalPoincare
public import FluidSingularSets.ScaleRegularity
public import FluidSingularSets.GaugeFrostman
public import FluidSingularSets.ShiftedCarleson
public import FluidSingularSets.RealCharge
public import FluidSingularSets.CompactLocalization
public import FluidSingularSets.TraceCost
public import FluidSingularSets.ParabolicRefinement
public import FluidSingularSets.GaugeFrostmanLimit
public import FluidSingularSets.GaugeTransport
public import FluidSingularSets.MixedPressure
public import FluidSingularSets.ActivityMeasurability
public import FluidSingularSets.ParabolicFrostmanGeometry
public import FluidSingularSets.GaugeFrostmanApproximations
public import FluidSingularSets.GaugeFrostmanConstruction
public import FluidSingularSets.SpatialTraceCoefficients
public import FluidSingularSets.ShiftedSpatialRepresentation
public import FluidSingularSets.MixedVelocityDecay
public import FluidSingularSets.IteratedFrostman
public import FluidSingularSets.SpatialTraceCarleson
public import FluidSingularSets.FrostmanCellGrowth
public import FluidSingularSets.FrostmanTraceEmbedding
public import FluidSingularSets.ShiftedCellRepresentation
public import FluidSingularSets.ActualEnergyControl
public import FluidSingularSets.GradientEnergyControl
public import FluidSingularSets.SymmetricMixedDecay
public import FluidSingularSets.CombinedWindowDecay
public import FluidSingularSets.VelocityOnlyBridge
public import FluidSingularSets.BoundedRegularity
public import FluidSingularSets.ConcreteTraceCarleson
public import FluidSingularSets.ConcreteTraceAE
public import FluidSingularSets.SymmetricChargeDecay
public import FluidSingularSets.FixedScaleRecurrence
public import FluidSingularSets.SymmetricCellMixedComparison
public import FluidSingularSets.CellMixedDissipation
public import FluidSingularSets.CompactCharge
public import FluidSingularSets.DyadicLogWeights
public import FluidSingularSets.ConcreteMassRatioTrace
public import FluidSingularSets.PointwiseGradientTrace
public import FluidSingularSets.CylinderCellComparison
public import FluidSingularSets.TraceActivityComparison
public import FluidSingularSets.PressureGradientFiveFourths
public import FluidSingularSets.DyadicActivitySequence
public import FluidSingularSets.LocalizedGradientPatch
public import FluidSingularSets.RawSingularPersistence
public import FluidSingularSets.GaugeTraceExclusion
public import FluidSingularSets.CompactGaugeNullity
public import FluidSingularSets.SuitableGaugeNullity
public import FluidSingularSets.WeightedVelocityPoincare
public import FluidSingularSets.WeightedMeanMotion
public import FluidSingularSets.CompactBoxDensity
public import FluidSingularSets.AcceleratedFrame
public import FluidSingularSets.AcceleratedEnergyAlgebra
public import FluidSingularSets.MeanMotionBound
public import FluidSingularSets.LocalStokesEnergy
public import FluidSingularSets.AcceleratedData
public import FluidSingularSets.NormalizedWeightedCutoff
public import FluidSingularSets.WeightedBallDivergence
public import FluidSingularSets.AcceleratedEnergy
public import FluidSingularSets.SmoothAcceleratedSuitability
public import FluidSingularSets.AcceleratedPressureLp
public import FluidSingularSets.AcceleratedLpStability
public import FluidSingularSets.StokesTestPoincare
public import FluidSingularSets.StrongLpProducts
public import FluidSingularSets.MeanSmoothApprox
public import FluidSingularSets.AcceleratedTubeLimit
public import FluidSingularSets.FischerPolynomial
public import FluidSingularSets.BallPolynomialInverse
public import FluidSingularSets.PolynomialBallDivergence

public import FluidSingularSets.StrongLpIntegrands
public import FluidSingularSets.WeakEquationLimit
public import FluidSingularSets.MovingRelativeVelocity

public import FluidSingularSets.LocalEnergyLimit
public import FluidSingularSets.AcceleratedPressureLimit
public import FluidSingularSets.BallBoundaryApproximation
public import FluidSingularSets.PolynomialBallMeanInverse

public import FluidSingularSets.AbsolutelyContinuousFrame
public import FluidSingularSets.HilbertBallBoundary
public import FluidSingularSets.PolynomialBallEnergy
public import FluidSingularSets.PolynomialBallRellich
public import FluidSingularSets.StokesPressureRecovery

public import FluidSingularSets.DenseHilbertLifts
public import FluidSingularSets.AcceleratedRegularity
public import FluidSingularSets.PolynomialBallDensity
public import FluidSingularSets.PolynomialBallMeanDensity
public import FluidSingularSets.BallDivergenceInverse
public import FluidSingularSets.UnitBallStokesPressure
public import FluidSingularSets.RealHilbertDual
public import FluidSingularSets.StokesPressureProjection
public import FluidSingularSets.UnitBallPressureProjection
public import FluidSingularSets.StokesGradientTest
public import FluidSingularSets.UnitBallPressureHarmonic
public import FluidSingularSets.LocalHarmonicDerivatives
public import FluidSingularSets.PressureGradientUniqueness
public import FluidSingularSets.SlidingMixedCost
public import FluidSingularSets.StokesEnergyVelocity

public import FluidSingularSets.RepeatedLogGauge
public import FluidSingularSets.StokesVectorForce
public import FluidSingularSets.StokesVectorForceLinear
public import FluidSingularSets.HarmonicC2
public import FluidSingularSets.UnitBallPressureC2
public import FluidSingularSets.StokesVectorPressureC2
public import FluidSingularSets.UnitBallPressureBounds
public import FluidSingularSets.StokesVectorPressureBounds
public import FluidSingularSets.ProjectedEnergyAlgebra
public import FluidSingularSets.BoxChargeReduction
public import FluidSingularSets.StokesNonlinearPressure

public import FluidSingularSets.SliceLpMeasurable
public import FluidSingularSets.SliceLpMoments
public import FluidSingularSets.WeakTimePressure
public import FluidSingularSets.StokesMomentumTime
public import FluidSingularSets.SmoothHarmonicEnergy
public import FluidSingularSets.PressureEnergyDual
public import FluidSingularSets.PressureEnergyForces
public import FluidSingularSets.PressureForceTime
public import FluidSingularSets.StokesPressureTimeIntegrability
public import FluidSingularSets.StokesPressureCurves
public import FluidSingularSets.StokesForceCurves
public import FluidSingularSets.UnitBallHarmonicGradient
public import FluidSingularSets.UnitBallHarmonicGradientPairing
public import FluidSingularSets.UnitBallHarmonicGradientMeasurable
public import FluidSingularSets.LocalHessianCalculus
public import FluidSingularSets.UnitBallHarmonicHessian

public import FluidSingularSets.ActualPressureCurve
public import FluidSingularSets.UnitBallHarmonicForceGradient
public import FluidSingularSets.UnitBallHarmonicForceExtension
public import FluidSingularSets.UnitBallHarmonicGradientCompatibility
public import FluidSingularSets.SuitableProjectedPressureTime
public import FluidSingularSets.HarmonicCorrectionCrossTerms
public import FluidSingularSets.SmoothProjectedDivergence
public import FluidSingularSets.SmoothHarmonicMomentum
public import FluidSingularSets.SmoothProjectedPressureCancellation

public import FluidSingularSets.WeakDerivativeGradientFree
public import FluidSingularSets.WeakContinuousTimePrimitive
public import FluidSingularSets.SuitableHarmonicGradientTime
public import FluidSingularSets.HarmonicScalarEnergyCancellation
public import FluidSingularSets.SmoothProjectedLocalEnergy
public import FluidSingularSets.HarmonicTimeSmoothApprox
public import FluidSingularSets.StrongMixedPairings
public import FluidSingularSets.MixedSlicePairings
public import FluidSingularSets.EndpointVelocityInterpolation
public import FluidSingularSets.SuitableVelocityTimeBound
public import FluidSingularSets.HarmonicSpatialSmoothApprox
public import FluidSingularSets.UniformMixedSlices
public import FluidSingularSets.CanonicalForcePressureValues
public import FluidSingularSets.UnitBallHarmonicForceHessian
public import FluidSingularSets.StrongOperatorCurveLimits
public import FluidSingularSets.HarmonicJointSmoothApprox

public import FluidSingularSets.ProjectedEnergyStrongLimit
public import FluidSingularSets.MixedWeightedVelocity
public import FluidSingularSets.ProjectedCaccioppoliAlgebra
public import FluidSingularSets.FullBallHarmonicRegularity

public import FluidSingularSets.SuitableHarmonicSmoothApprox
public import FluidSingularSets.HarmonicHessianSmoothApprox

public import FluidSingularSets.StokesTensorPressurePoisson
public import FluidSingularSets.ProjectedCutoffConvection

public import FluidSingularSets.BallStokesPressureProjection
public import FluidSingularSets.HarmonicPressureOscillation
public import FluidSingularSets.SuitableViscousPressureHarmonic
public import FluidSingularSets.JointTopSliceClasses
public import FluidSingularSets.ProjectedCutoffSobolev
public import FluidSingularSets.ProjectedWeightedConvection

public import FluidSingularSets.SuitableProjectedLocalEnergy
public import FluidSingularSets.ProjectedCutoffMixedEnergy
public import FluidSingularSets.BallStokesPressureSources
public import FluidSingularSets.MixedQuadraticSources
public import FluidSingularSets.SuitableProjectedPressureIdentification

public import FluidSingularSets.BallHarmonicPressureDecay
public import FluidSingularSets.SuitableBallPressureHarmonic
public import FluidSingularSets.LocalBoxPressureForces
public import FluidSingularSets.SuitableProjectedWeakGradient
public import FluidSingularSets.StokesPressureMixedBounds
public import FluidSingularSets.ProjectedHarmonicSourceBounds
public import FluidSingularSets.MixedSpatialMeans

public import FluidSingularSets.BallCenteredPressureOperator

public import FluidSingularSets.BallStokesUnitCompatibility

public import FluidSingularSets.SuitableProjectedVelocityEnergy

public import FluidSingularSets.LocalBoxPressureEnergy

public import FluidSingularSets.LocalBoxEnergyForces

public import FluidSingularSets.TestedTimeEnergy

public import FluidSingularSets.SuitableProjectedTimeEnergy

public import FluidSingularSets.LocalBoxProjectedTime

public import FluidSingularSets.LocalBoxProjectedLocalEnergy

public import FluidSingularSets.LocalBoxProjectedTimeEnergy

public import FluidSingularSets.UnitBallPressureMixedBounds

public import FluidSingularSets.UnitBallPressureOscillationMoment

public import FluidSingularSets.TestedTimeEnergyBounds

public import FluidSingularSets.ProjectedCylinderCutoff

public import FluidSingularSets.FullBallHarmonicOperators
public import FluidSingularSets.FullBallHarmonicValues
public import FluidSingularSets.FullBallProjectedSources
public import FluidSingularSets.LocalBoxProjectedWeakGradient
public import FluidSingularSets.ProjectedCutoffErrors
public import FluidSingularSets.SuitablePressureMeanPairings
public import FluidSingularSets.WeightedProjectedConvection

public import FluidSingularSets.FullBallProjectedWeakGradient
public import FluidSingularSets.FullBallProjectedData
public import FluidSingularSets.FullBallPressureMeanPairings
public import FluidSingularSets.FullBallSpatialSmoothApprox
public import FluidSingularSets.FullBallSpatialKernels
public import FluidSingularSets.ProjectedViscousMixedPairing
public import FluidSingularSets.WeightedProjectedSobolev

/-! # Singular-set refinements for suitable weak Navier–Stokes solutions

This root exports the completed supporting development. The three target declarations for the
two requested results are in `Challenge.lean`. Main proof completion is tracked separately in
`Solution.lean`.
-/
