-- Copyright (c) 2026 FluidSingularSets contributors.
-- Released under Apache 2.0 license as described in the file LICENSE.

module

public import CKN.Foundation.Sobolev.TestFunction
public import CKN.Foundation.Parabolic.Basic
public import Mathlib.Analysis.InnerProductSpace.Dual
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.InnerProductSpace.Projection.Basic
public import Mathlib.LinearAlgebra.Isomorphisms
public import Mathlib.MeasureTheory.Function.L2Space
public import Mathlib.MeasureTheory.SpecificCodomains.WithLp

/-!
# The variational energy part of the local Stokes problem

The energy space is constructed as the closed subspace of `L²` generated by the
gradients of actual smooth compactly supported vector tests. Its divergence is
the continuous matrix trace map. Riesz representation on the closed divergence
kernel constructs the variational Stokes solution and proves its energy bound.
The residual factors through the actual divergence range, without assuming a
pressure projector or an inf-sup estimate.

Recovering a mean-zero `L²` pressure from this factorization additionally needs
a bounded right inverse for divergence on a ball. This module does not claim
that estimate or the pressure recovery theorem.
-/

@[expose] public section

open MeasureTheory Set CKN
open CKN.Foundation.Parabolic
open scoped ENNReal Topology BigOperators

set_option autoImplicit false

noncomputable section

namespace FluidSingularSets

/-- The Euclidean Hilbert norm on spatial gradient matrices. -/
abbrev StokesGradientMatrix := EuclideanSpace ℝ (Fin 3 × Fin 3)

/-- The ambient Hilbert space for zero-boundary velocity gradients. -/
abbrev StokesGradientL2 (U : Set Vec3) :=
  Lp StokesGradientMatrix 2 (volume.restrict U)

/-- Three genuine smooth compactly supported scalar tests form a vector test. -/
abbrev StokesVectorTest (U : Set Vec3) := Fin 3 → WeakTestFunction U

/-- The classical spatial gradient, with derivative index first. -/
def stokesTestGradient {U : Set Vec3} (φ : StokesVectorTest U) :
    Vec3 → StokesGradientMatrix :=
  fun x ↦ WithLp.toLp 2 (fun ij ↦ (φ ij.2).partialDeriv ij.1 x)

/-- Compactly supported smooth test gradients genuinely belong to `L²`. -/
theorem stokesTestGradient_memLp {U : Set Vec3} (φ : StokesVectorTest U) :
    MemLp (stokesTestGradient φ) 2 (volume.restrict U) := by
  apply MemLp.of_eval_piLp
  intro ij
  have hcont : Continuous ((φ ij.2).partialDeriv ij.1) :=
    ((φ ij.2).contDiff.continuous_fderiv (by simp)).clm_apply continuous_const
  have hcompact : HasCompactSupport ((φ ij.2).partialDeriv ij.1) :=
    (φ ij.2).hasCompactSupport.fderiv_apply (𝕜 := ℝ) (basisVec ij.1)
  exact (hcont.memLp_of_hasCompactSupport hcompact).mono_measure Measure.restrict_le_self

/-- A test gradient as an actual `L²` equivalence class. -/
def stokesTestGradientL2 {U : Set Vec3} (φ : StokesVectorTest U) :
    StokesGradientL2 U :=
  (stokesTestGradient_memLp φ).toLp (stokesTestGradient φ)

/-- The zero-boundary energy completion, constructed inside the ambient Hilbert space. -/
def stokesGradientEnergySpace (U : Set Vec3) :
    ClosedSubmodule ℝ (StokesGradientL2 U) :=
  (Submodule.span ℝ (range (stokesTestGradientL2 (U := U)))).closure

/-- Every genuine test gradient belongs to the constructed energy space. -/
theorem stokesTestGradientL2_mem {U : Set Vec3} (φ : StokesVectorTest U) :
    stokesTestGradientL2 φ ∈ stokesGradientEnergySpace U := by
  apply Submodule.le_topologicalClosure
  exact Submodule.subset_span ⟨φ, rfl⟩

/-- The same test gradient, bundled in the energy space. -/
def stokesEnergyTest {U : Set Vec3} (φ : StokesVectorTest U) :
    stokesGradientEnergySpace U :=
  ⟨stokesTestGradientL2 φ, stokesTestGradientL2_mem φ⟩

/-- Matrix trace is the divergence of a velocity gradient. -/
def stokesMatrixTrace : StokesGradientMatrix →L[ℝ] ℝ :=
  ∑ i : Fin 3, PiLp.proj 2 (fun _ : Fin 3 × Fin 3 ↦ ℝ) (i, i)

@[simp]
theorem stokesMatrixTrace_apply (A : StokesGradientMatrix) :
    stokesMatrixTrace A = ∑ i : Fin 3, A (i, i) := by
  simp [stokesMatrixTrace]

/-- Divergence on the energy completion, defined by the actual matrix trace. -/
def stokesEnergyDivergence (U : Set Vec3) :
    stokesGradientEnergySpace U →L[ℝ] Lp ℝ 2 (volume.restrict U) :=
  (stokesMatrixTrace.compLpL 2 (volume.restrict U)).comp
    (stokesGradientEnergySpace U).toSubmodule.subtypeL

/-- On genuine tests the constructed divergence equals the classical divergence. -/
theorem stokesEnergyDivergence_test_ae {U : Set Vec3} (φ : StokesVectorTest U) :
    stokesEnergyDivergence U (stokesEnergyTest φ) =ᵐ[volume.restrict U]
      fun x ↦ ∑ i : Fin 3, (φ i).partialDeriv i x := by
  have hcomp := stokesMatrixTrace.coeFn_compLpL
    (p := 2) (μ := volume.restrict U) (stokesTestGradientL2 φ)
  have htest := (stokesTestGradient_memLp φ).coeFn_toLp
  change stokesMatrixTrace.compLpL 2 (volume.restrict U) (stokesTestGradientL2 φ)
    =ᵐ[volume.restrict U] _
  filter_upwards [hcomp, htest] with x hx ht
  change stokesTestGradientL2 φ x = stokesTestGradient φ x at ht
  rw [hx, ht]
  simp [stokesTestGradient]

/-- The closed divergence kernel supplies the Hilbert solenoidal energy space. -/
def stokesSolenoidalEnergySpace (U : Set Vec3) :
    ClosedSubmodule ℝ (stokesGradientEnergySpace U) where
  toSubmodule := (stokesEnergyDivergence U).ker
  isClosed' := (stokesEnergyDivergence U).isClosed_ker

/-- Classical divergence-free compact tests belong to the constructed kernel. -/
theorem stokesEnergyTest_mem_solenoidal {U : Set Vec3} (φ : StokesVectorTest U)
    (hdiv : ∀ x, ∑ i : Fin 3, (φ i).partialDeriv i x = 0) :
    stokesEnergyTest φ ∈ stokesSolenoidalEnergySpace U := by
  change stokesEnergyDivergence U (stokesEnergyTest φ) = 0
  apply Lp.ext
  exact (stokesEnergyDivergence_test_ae φ).trans (ae_of_all _ hdiv) |>.trans
    (Lp.coeFn_zero _ _ _).symm

/-- An actual continuous force functional on the constructed zero-boundary energy space. -/
abbrev StokesEnergyForce (U : Set Vec3) := stokesGradientEnergySpace U →L[ℝ] ℝ

/-- Riesz representation constructs the variational Stokes gradient in the divergence kernel. -/
def stokesEnergySolution {U : Set Vec3} (F : StokesEnergyForce U) :
    stokesSolenoidalEnergySpace U :=
  (InnerProductSpace.toDual ℝ (stokesSolenoidalEnergySpace U)).symm
    (F.comp (stokesSolenoidalEnergySpace U).toSubmodule.subtypeL)

/-- The variational identity holds against every element of the divergence kernel. -/
theorem stokesEnergySolution_firstVariation {U : Set Vec3} (F : StokesEnergyForce U)
    (v : stokesSolenoidalEnergySpace U) :
    inner ℝ (stokesEnergySolution F) v = F v := by
  exact InnerProductSpace.toDual_symm_apply

/-- The gradient energy is bounded by the dual force norm, with constant one. -/
theorem stokesEnergySolution_norm_le {U : Set Vec3} (F : StokesEnergyForce U) :
    ‖stokesEnergySolution F‖ ≤ ‖F‖ := by
  rw [stokesEnergySolution, (InnerProductSpace.toDual ℝ
    (stokesSolenoidalEnergySpace U)).symm.norm_map]
  calc
    _ ≤ ‖F‖ * ‖(stokesSolenoidalEnergySpace U).toSubmodule.subtypeL‖ :=
      ContinuousLinearMap.opNorm_comp_le _ _
    _ ≤ ‖F‖ * 1 := mul_le_mul_of_nonneg_left
      ((stokesSolenoidalEnergySpace U).toSubmodule.norm_subtypeL_le) (norm_nonneg F)
    _ = ‖F‖ := mul_one _

/-- Testing with the solution gives the exact energy equality. -/
theorem stokesEnergySolution_energy {U : Set Vec3} (F : StokesEnergyForce U) :
    ‖stokesEnergySolution F‖ ^ 2 = F (stokesEnergySolution F) := by
  simpa only [real_inner_self_eq_norm_sq] using
    stokesEnergySolution_firstVariation F (stokesEnergySolution F)

/-- In particular the equation holds against every genuine divergence-free smooth test. -/
theorem stokesEnergySolution_test {U : Set Vec3} (F : StokesEnergyForce U)
    (φ : StokesVectorTest U)
    (hdiv : ∀ x, ∑ i : Fin 3, (φ i).partialDeriv i x = 0) :
    inner ℝ (stokesEnergySolution F : stokesGradientEnergySpace U)
      (stokesEnergyTest φ) = F (stokesEnergyTest φ) := by
  exact stokesEnergySolution_firstVariation F
    ⟨stokesEnergyTest φ, stokesEnergyTest_mem_solenoidal φ hdiv⟩

/-- The constructed energy solution is unique. -/
theorem stokesEnergySolution_unique {U : Set Vec3} (F : StokesEnergyForce U)
    (w : stokesSolenoidalEnergySpace U)
    (hw : ∀ v : stokesSolenoidalEnergySpace U, inner ℝ w v = F v) :
    w = stokesEnergySolution F := by
  apply (InnerProductSpace.toDual ℝ (stokesSolenoidalEnergySpace U)).injective
  ext v
  exact (hw v).trans (stokesEnergySolution_firstVariation F v).symm

/-- An actual `L²` stress tensor defines the force `-div T` on the constructed space. -/
def stokesTensorForce {U : Set Vec3} (T : StokesGradientL2 U) : StokesEnergyForce U :=
  (innerSL ℝ T).comp (stokesGradientEnergySpace U).toSubmodule.subtypeL

/-- The dual force norm is controlled by the genuine `L²` tensor norm. -/
theorem stokesTensorForce_norm_le {U : Set Vec3} (T : StokesGradientL2 U) :
    ‖stokesTensorForce T‖ ≤ ‖T‖ := by
  calc
    _ ≤ ‖innerSL ℝ T‖ * ‖(stokesGradientEnergySpace U).toSubmodule.subtypeL‖ :=
      ContinuousLinearMap.opNorm_comp_le _ _
    _ ≤ ‖innerSL ℝ T‖ * 1 := mul_le_mul_of_nonneg_left
      ((stokesGradientEnergySpace U).toSubmodule.norm_subtypeL_le) (norm_nonneg _)
    _ = ‖T‖ := by rw [mul_one, innerSL_apply_norm]

/-- The tensor-source Stokes gradient satisfies the genuine constant-one energy bound. -/
theorem stokesTensorSolution_norm_le {U : Set Vec3} (T : StokesGradientL2 U) :
    ‖stokesEnergySolution (stokesTensorForce T)‖ ≤ ‖T‖ :=
  (stokesEnergySolution_norm_le _).trans (stokesTensorForce_norm_le T)

/-- Its equation is the literal weak tensor-forcing identity against smooth solenoidal tests. -/
theorem stokesTensorSolution_test {U : Set Vec3} (T : StokesGradientL2 U)
    (φ : StokesVectorTest U)
    (hdiv : ∀ x, ∑ i : Fin 3, (φ i).partialDeriv i x = 0) :
    inner ℝ (stokesEnergySolution (stokesTensorForce T) : stokesGradientEnergySpace U)
      (stokesEnergyTest φ) =
        ∫ x in U, inner ℝ (T x) (stokesTestGradient φ x) := by
  rw [stokesEnergySolution_test _ φ hdiv]
  change inner ℝ T (stokesTestGradientL2 φ) = _
  rw [L2.inner_def]
  apply integral_congr_ae
  filter_upwards [(stokesTestGradient_memLp φ).coeFn_toLp] with x hx
  exact congrArg (inner ℝ (T x)) hx

/-- The remaining force is a continuous functional vanishing on divergence-free tests. -/
def stokesEnergyResidual {U : Set Vec3} (F : StokesEnergyForce U) :
    StokesEnergyForce U :=
  F - innerSL ℝ (stokesEnergySolution F : stokesGradientEnergySpace U)

/-- The pressure residual is bounded in the actual energy dual norm. -/
theorem stokesEnergyResidual_norm_le {U : Set Vec3} (F : StokesEnergyForce U) :
    ‖stokesEnergyResidual F‖ ≤ 2 * ‖F‖ := by
  unfold stokesEnergyResidual
  calc
    _ ≤ ‖F‖ + ‖innerSL ℝ (stokesEnergySolution F : stokesGradientEnergySpace U)‖ :=
      norm_sub_le F (innerSL ℝ (stokesEnergySolution F : stokesGradientEnergySpace U))
    _ = ‖F‖ + ‖stokesEnergySolution F‖ := by rw [innerSL_apply_norm]; rfl
    _ ≤ ‖F‖ + ‖F‖ := by gcongr; exact stokesEnergySolution_norm_le F
    _ = 2 * ‖F‖ := by ring

/-- Vanishing on the whole kernel is proved from the variational identity. -/
theorem stokesEnergyResidual_eq_zero_of_divergence_eq_zero {U : Set Vec3}
    (F : StokesEnergyForce U) (v : stokesGradientEnergySpace U)
    (hdiv : stokesEnergyDivergence U v = 0) :
    stokesEnergyResidual F v = 0 := by
  have hv : v ∈ stokesSolenoidalEnergySpace U := hdiv
  have h := stokesEnergySolution_firstVariation F ⟨v, hv⟩
  change F v - inner ℝ (stokesEnergySolution F : stokesGradientEnergySpace U) v = 0
  exact sub_eq_zero.mpr h.symm

/-- The residual therefore factors through the actual divergence range. No norm
estimate for this factor in the `L²` pressure norm is asserted. -/
theorem exists_stokesPressureRangeFunctional {U : Set Vec3} (F : StokesEnergyForce U) :
    ∃ p : (stokesEnergyDivergence U).range →ₗ[ℝ] ℝ,
      ∀ v : stokesGradientEnergySpace U,
        p ⟨stokesEnergyDivergence U v,
          (stokesEnergyDivergence U).toLinearMap.mem_range_self v⟩ =
            stokesEnergyResidual F v := by
  let D := (stokesEnergyDivergence U).toLinearMap
  have hker : D.ker ≤ (stokesEnergyResidual F).toLinearMap.ker := by
    intro v hv
    exact stokesEnergyResidual_eq_zero_of_divergence_eq_zero F v hv
  let q := D.ker.liftQ (stokesEnergyResidual F).toLinearMap hker
  refine ⟨q.comp D.quotKerEquivRange.symm.toLinearMap, ?_⟩
  intro v
  change q (D.quotKerEquivRange.symm ⟨D v, D.mem_range_self v⟩) = _
  rw [D.quotKerEquivRange_symm_apply_image v (D.mem_range_self v)]
  rfl

end FluidSingularSets
